version: '3'

services:
  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: shoppingdb
    restart: always
  app_shopping:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: r2dbc:mysql://db:3306/shoppingdb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456

